name: my_flutter
description: "My first flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  shared_preferences: ^2.2.3

  logger: ^2.2.0

  provider: ^6.1.2

  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

